<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BNPS8DG" failures="1" tests="1" name="Test" time="31.705" errors="0" timestamp="2024-03-12T02:50:36 IST">
  <testcase classname="tests.TaskCreate" name="createTask" time="26.062">
    <failure type="java.lang.AssertionError" message="Confirmation message is differnet than Successfully Saved expected [1 new task was added to the customer &amp;quot;HDFC&amp;quot;, project &amp;quot;Investment banking&amp;quot;] but found [1 new task was added to the customer &amp;quot;HDFC&amp;quot;, project &amp;quot;Investment banking&amp;quot;.]">
      <![CDATA[java.lang.AssertionError: Confirmation message is differnet than Successfully Saved expected [1 new task was added to the customer "HDFC", project "Investment banking"] but found [1 new task was added to the customer "HDFC", project "Investment banking".]
at tests.TaskCreate.createTask(TaskCreate.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- createTask -->
</testsuite> <!-- Test -->
